# Generated by Django 3.2 on 2021-04-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_event', models.DateTimeField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('lost', 'lost'), ('find', 'find')], default='lost', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('animal_kind', models.CharField(choices=[('dogs', 'dogs'), ('cats', 'cats')], max_length=20)),
                ('animal_sex', models.CharField(blank=True, choices=[('boy', 'boy'), ('girl', 'girl')], max_length=20, null=True)),
                ('castrated', models.BooleanField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='images/')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='posts.post')),
            ],
        ),
    ]
